name: backend-tests

on:
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-asyncio httpx

      # ðŸ”½ YENÄ°: Lint quraÅŸdÄ±r vÉ™ iÅŸlÉ™
      - name: Install linter (ruff)
        run: pip install ruff

      - name: Lint (ruff)
        run: ruff check . --output-format=github

      - name: Run tests
        env:
          PYTHONPATH: .
        run: pytest -q
